### ISSUE TITLE
Incorrect equals implementation

### ISSUE THREAD

**Issue by MarkiyanFostyak** [Roman6917/Polynomial#3]
https://github.com/Roman6917/Polynomial/blob/a8c2e51ce56e91747a2c9dde29e1a11933bf7f6d/Polynomial/Program.cs#L69
This is not a correct condition. For example `2^4 == 4^2`, but this method will return `false`.

**Comment by OHopiak** [comment]
Please, check this condition again, it works for only a^b == a^b
